name: CI/CD Pipeline - Ostad DevOps Project 3

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: Test and Upload results
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm run check | tee test-results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt
